config/routes.rb
Rails.application.routes.draw do
	root to: 'users#index'

  devise_for :users

  resources :accounts
  resources :transactions
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user

	has_many :transactions, dependent: :destroy

	validates :account_number, presence: true
	validates :account_number, uniqueness: true

	def deposit(deposit_amount)
		with_lock do
			updated_amount = amount.to_i + deposit_amount
	  	update(amount: updated_amount)
	  	transaction = transactions.create(amount: deposit_amount, balance: updated_amount, 
	  		transaction_type: Transaction.transaction_types[:deposit])
	  	UserMailer.deliver_email(user, transaction, 'deposited').deliver_now
	  end
	end

	def withdraw(withdraw_amount)
		with_lock do
      updated_amount = amount.to_i - withdraw_amount
      update(amount: updated_amount)
      transaction = transactions.create(amount: withdraw_amount, balance: updated_amount, 
      	transaction_type: Transaction.transaction_types[:withdraw])
      UserMailer.deliver_email(user, transaction, 'debited').deliver_now
	  end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account

  enum transaction_type: { deposit: 'Deposit', withdraw: 'Withdraw' }

  def self.header_format(sheet)
  	h_format = sheet.add_format
		h_format.set_bold
		h_format.set_color('green')
		h_format.set_align('center')
		h_format
  end

  def self.row_format(sheet)
  	r_format = sheet.add_format
		r_format.set_color('Black')
		r_format.set_align('center')
		r_format
  end

  def self.generate_transaction_history(user_ids, from, to)
  	path = Rails.root.join('tmp', "transaction_history.xlsx").to_path
    file = File.new(path, "w")
  	accounts = Account.where(user_id: user_ids).includes(:user, :transactions)

  	workbook = WriteXLSX.new(file)
  	worksheet = workbook.add_worksheet
  	h_format = Transaction.header_format(workbook)
  	r_format = Transaction.row_format(workbook)

		row = 1
  	accounts.each do |account|
  		transactions = if from.present? && to.present?
  			account.transactions.where(created_at: from..to)
  		else
  			account.transactions
  		end

  		if transactions.present?
	  		worksheet.merge_range("A#{row}:C#{row + 1}", "Name - #{account.user.user_name}", h_format)
	  		worksheet.merge_range("D#{row}:G#{row + 1}", "Acc. No. - #{account.account_number}", h_format)
	  		row += 2

	  		worksheet.merge_range("A#{row}:C#{row + 1}", 'Date', h_format)
	  		worksheet.merge_range("D#{row}:D#{row + 1}", 'Amount', h_format)
	  		worksheet.merge_range("E#{row}:F#{row + 1}", 'Transaction Type', h_format) 
	  		worksheet.merge_range("G#{row}:G#{row + 1}", 'Balance', h_format)
	  		row += 1

	  		transactions.each_with_index do |transaction, j|
	  			row += 1
	  			worksheet.merge_range("A#{row}:C#{row}", transaction.created_at.strftime("%b %d, %Y"), r_format)
	  			worksheet.write(row - 1, 3, transaction.amount)
	  			worksheet.merge_range("E#{row}:F#{row}", transaction.transaction_type, r_format)				
					worksheet.write(row - 1, 6, transaction.balance)
				end
			end

			row += 1
		end
		workbook.close

		path
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account, dependent: :destroy
  
  accepts_nested_attributes_for :account

  validates :user_name, :role, presence: true

  enum role: { manager: 'manager', user: 'user' }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.includes(:transactions).find(params[:id])
  end

  def new
  end

  def edit 
    @account = Account.find_by(user_id: params[:id])
  end

  def create #deposit
    account = Account.find_by(account_number: params[:account][:account_number])
    if account
      account.deposit(params[:account][:amount].to_i)
      redirect_to root_path
    else
      flash[:error] = "Account Number does not exist."
      render :new
    end
  end

  def update #withdraw
    @account = current_user.account
    if @account.amount >= params[:amount].to_i
      @account.withdraw(params[:amount].to_i)
      redirect_to root_path
    else
      flash[:error] = "Deposit amount is greater than total amount"
      render :edit
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :role, account_attributes: [:account_number]])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
  	path = Transaction.generate_transaction_history(params[:user_ids], params[:from], params[:to])
  	send_file path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.where(role: 'user')
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_transaction.html.erb
<div>
	<h4>Total Amount: <%= account.amount %></h4>
	<div>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Amount</th>
					<th>Transaction Type</th>
					<th>Transaction Date</th>
					<th>Balance</th>
				</tr>
			</thead>
			<tbody>
				<% account.transactions.each do |transaction| %>
					<tr>
						<td><%= transaction.amount %></td>
						<td><%= transaction.transaction_type %></td>
						<td><%= transaction.created_at.strftime("%b %d, %Y") %></td>
						<td><%= transaction.balance %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div><%= link_to 'Back', root_path %></div>
	</div>
</div>

app/views/accounts/edit.html.erb
<div>
	<h4>Withdraw Amount</h4>

	<%= form_tag :account, url: account_path(@account.id), method: :put do |f| %>
	  <div class="row">
	  	<div class='col-sm-4'>
        <div class="form-group">
			    <%= label_tag :amount %><br />
			    <%= number_field_tag :amount, nil, class: 'form-control' %>
	  		</div>
	  		<div class="text-danger">
					<% if flash.any? %>
						<%= flash[:error] %>
					<% end %>
				</div>
			</div>
	  </div>

	  <div class="actions">
	    <%= submit_tag "submit" %>
	  </div></br>
	  <div><%= link_to 'Back', root_path %></div>
	<% end %>
</div>

app/views/accounts/new.html.erb
<div>
	<h4>Deposit Amount</h4>
	<%= form_for :account, url: accounts_path, method: :post do |f| %>
		<div class="row">
	  	<div class='col-sm-6'>
        <div class="form-group">
			    <%= f.label :account_number %><br />
			    <%= f.number_field :account_number, id: 'number', class: 'form-control' %>
			  </div>
			  <div class="text-danger">
					<% if flash.any? %>
						<%= flash[:error] %>
					<% end %>
				</div>
			</div>
	  </div>

	  <div class="row">
	  	<div class='col-sm-6'>
        <div class="form-group">
			    <%= f.label :amount %><br />
			    <%= f.number_field :amount, class: 'form-control' %>
	  		</div>
			</div>
	  </div>

	  <div class="actions">
	    <%= f.submit "submit" %>
	  </div></br>
	  <div><%= link_to 'Back', root_path %></div>
	<% end %>
</div>

app/views/accounts/show.html.erb
<%= render :partial => 'transaction', :locals => {:account => @account} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankingSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
		  <a class="navbar-brand" href="#">Banking System</a>
		  <ul class="navbar-nav pull-right">
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          <%= current_user.email if user_signed_in? %>
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
	        </div>
	      </li>
	    </ul>
		</nav>
		<% if notice || alert %>
	  	<p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>
	  <% end %>
    <div class="container">
		  <%= yield %>
		</div>
  </body>
</html>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/users/index.html.erb
<div>
	<div class="row">
		<div class='col-sm-2'>
			<%= current_user.role.capitalize %>: <%= current_user.user_name %>
		</div>
		<% if current_user.manager? %>
			<div class='col-sm-2'>
				<%= link_to "Deposit", new_account_path(id: current_user.id) %>
			</div>
		<% end %>
		<div class='col-sm-2'>
			<% if current_user.user? %>
				<%= link_to "Withdraw", edit_account_path(current_user.id) %>
			<% end %>
		</div>
	</div></br>

	<% if current_user.manager? %>
		<%= form_tag transactions_path, method: :post do %>
			<div>
			  <div class="row">
			  	<div class='col-sm-4'>
	          <div class="form-group">
	          	<label>From</label>
	            <%= text_field_tag 'from', nil, class: 'form-control', 'data-provide' => 'datepicker' %>
	          </div>
	        </div>
	        <div class='col-sm-4'>
	          <div class="form-group">
	          	<label>To</label>
  	          <%= text_field_tag 'to', nil, class: 'form-control', 'data-provide' => 'datepicker' %>
	          </div>
	        </div>
			  </div>
			</div>
			<div>
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Select</th>
							<th>User Name</th>
							<th>Account Number</th>
							<th>Check Balance</th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
							<tr>
								<td><%= check_box_tag 'user_ids[]', user.id %></td>
								<td><%= user.user_name %></td>
								<td><%= user.account.account_number %></td>
								<td><%= link_to 'Enquiry', account_path(user.account.id) %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
				<button type="submit" value="Submit">Genare transaction histories</button>
			</div>
		<% end %>
	<% else %>
		<%= render :partial => 'accounts/transaction', :locals => {:account => current_user.account} %>
	<% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
  	$.fn.datepicker.defaults.format = "yyyy/mm/dd";
    $('#datepicker').datepicker();
    $('#datetimepicker1').datetimepicker({
    	format: 'L'
    });
  });
</script>